# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='university_logos')),
                ('description', tinymce.models.HTMLField(max_length=4000)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
