# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('name',), 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='university',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
