# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 18:23
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_edu', '0003_auto_20160121_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
