# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160110_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
