# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160110_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='subscribed',
            field=models.BooleanField(default=False, help_text='Whether this user subscribed to a paid plan'),
        ),
    ]
