# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='college_year',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
