# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Whether this content can only be viewed by subscribed users'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Whether this content can only be viewed by subscribed users'),
        ),
    ]
