# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0003_auto_20160123_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=tinymce.models.HTMLField(max_length=30000),
        ),
    ]
