# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:00
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0004_auto_20160130_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000),
        ),
    ]
