# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 18:22
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0005_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
