# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0006_auto_20160204_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_ready.Category')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=('job_ready.category',),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.ManyToManyField(null=True, related_name='articles', to='job_ready.Year'),
        ),
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.ManyToManyField(null=True, related_name='videos', to='job_ready.Year'),
        ),
    ]
