# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 17:34
from __future__ import unicode_literals

from django.db import migrations


def create_years(apps, schema_editor):
    Year = apps.get_model("job_ready", "Year")
    year_map = {
        'First Year': 'Content for first years',
        'Second Year': 'Content for second years',
        'Third Year': 'Content for third years',
        'Fourth Year': 'Content for fourth years',
    }

    for key, val in year_map.iteritems():
        Year.objects.create(name=key, short_description=val)


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0007_auto_20160614_1729'),
    ]

    operations = [
        migrations.RunPython(create_years)
    ]
