# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0010_auto_20160615_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('year_integer',)},
        ),
    ]
