# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_ready', '0011_auto_20160615_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('proxy_storage_name', models.CharField(max_length=50)),
                ('original_storage_path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
